bundle:
  name: "my_mlops_bundle_stage"

jobs:
  - name: "my_training_job_stage"
    tasks:
      - task_key: "train_classification_model_stage"
        notebooks:
          - path: "/Repos/my-mlops-repo-stage/notebooks/stage/training.ipynb"
        new_cluster:
          spark_version: "13.0.x-scala2.12"
          node_type_id: "i3.xlarge"
          num_workers: 2
        libraries: []
        timeout_seconds: 3600
        schedule:
          # e.g., Monday at 03:00
          quartz_cron_expression: "0 3 ? * MON *"
          timezone_id: "UTC"

  - name: "my_inference_job_stage"
    tasks:
      - task_key: "run_inference_stage"
        notebooks:
          - path: "/Repos/my-mlops-repo-stage/notebooks/stage/inference.ipynb"
        new_cluster:
          spark_version: "13.0.x-scala2.12"
          node_type_id: "i3.xlarge"
          num_workers: 2
        libraries: []
        timeout_seconds: 3600
        schedule:
          # daily at 04:00
          quartz_cron_expression: "0 4 * * * ?"
          timezone_id: "UTC"
