bundle:
  name: "my_mlops_bundle_stage"

jobs:
  - name: "my_training_job_stage"
    tasks:
      - task_key: "train_classification_model_stage"
        notebooks:
          - path: "/Repos/pochireddygari@gmail.com/wgu-assesment-stage/notebooks/stage/training.ipynb"
        new_cluster:
          spark_version: "13.0.x-scala2.12"
          node_type_id: "i3.large"
          num_workers: 1
        libraries: []
        timeout_seconds: 1800
        schedule:
          quartz_cron_expression: "0 10 * * * ?"
          timezone_id: "UTC"

  - name: "my_inference_job_stage"
    tasks:
      - task_key: "run_inference_stage"
        notebooks:
          - path: "/Repos/pochireddygari@gmail.com/wgu-assesment-stage/notebooks/stage/inference.ipynb"
        new_cluster:
          spark_version: "13.0.x-scala2.12"
          node_type_id: "i3.large"
          num_workers: 1
        libraries: []  
        timeout_seconds: 1800
        schedule:
          quartz_cron_expression: "0 11 * * * ?"
          timezone_id: "UTC"
